version: "3"
services:
  db:
    image: mysql:5.7
    container_name: "MySQL_Database_Flask"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  api:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: server
    volumes:
      - ./app:/app
    depends_on:
      - db
    links:
      - db
    ports:
      - "5000:5000"
    restart: on-failure
    command: ["./wait-for-it.sh", "db:3306", "--", "/bin/bash", "./create.sh"]
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: 'redis:latest'
    container_name: "redis_server"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    restart: always
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /sessions
